apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: docker-desktop
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50