apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest

        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql:3306"
        - name: WORDPRESS_DB_NAME
          value: "project"
        - name: WORDPRESS_DB_USER
          value: "cloudbreak"
        - name: WORDPRESS_DB_PASSWORD
          value: "cloudbreak2"
        ports:
        - containerPort: 8080
      